### PR TITLE
allow succeeded by list, closes #16

### LINKED ISSUE #16: Allow succeeded_by_phrase to take a list, and match if any are true
Let's say you only want to match if the following word is in `["height", "value", "size", "number"]`. You might try adding to your match.json:

```json
"match_hook": [
            {
                "name": "succeeded_by_phrase",
                "args": ["height", "value", "size", "number"],
                "match_if_predicate_is": true
            }
]
```

This will raise when it tries to call `lower()` on `args`, since it assumes it gets a string. Maybe you try

```json
"match_hook": [
            {
                "name": "succeeded_by_phrase",
                "args": "height",
                "match_if_predicate_is": true
            },
            {
                "name": "succeeded_by_phrase",
                "args": "value",
                "match_if_predicate_is": true
            },
            {
                "name": "succeeded_by_phrase",
                "args": "size",
                "match_if_predicate_is": true
            },
            {
                "name": "succeeded_by_phrase",
                "args": "number",
                "match_if_predicate_is": true
            }
        ]
```

This also doesn't work (empirically), and the syntax is horrible and verbose.

Action: make the first syntax work.

### PR DESCRIPTION
**Pull request by sam-qordoba**
This allows passing succeeded_by_phrase an arg that is a list.

Well, it felt weird to just do this for `succeeded_by_phrase` so now all the preceded/succeeded by match hooks support lists. Also fixed some typos while in there, and improved types.

There is some WET code in here... but I didn't want to spend time optimizing... Sorry 😬

### CODE REVIEW

**Comment by sam-qordoba** [comment]
NOTE: This has been released, v 0.12.0 https://pypi.org/project/replacy/0.12.0/

We can take it down if it doesn't pass CR

**Comment by sam-qordoba** [comment]
used here https://github.com/Qordobacode/service.plain.language/pull/88

**Comment by sam-qordoba** [comment]
@melisa-qordoba  did you bring this code in some other way? I see this PR is open, but it showed up on my master branch...

**Comment by melisa-qordoba** [comment]
> @melisa-qordoba did you bring this code in some other way? I see this PR is open, but it showed up on my master branch...

Yes. It was shipped here: https://github.com/Qordobacode/replaCy/commit/751d95a050a3a90488dc05312ea1687647525b5a

The story: introduced huge changes. Then saw your PR opened and ... conflicting. So merged both into one plus added more tests (which were left as todo).

**Pull request closed without merging**
