### PR TITLE
ENG-8226 support spacy3

### PR DESCRIPTION
**Pull request by manhal-daaboul**

### CODE REVIEW

**Comment by sam-qordoba** [comment]
Sweet!

So now:
* support spaCy >= v3!
* instead of copying the code for testing that the positive cases match and negative cases don't that's just an import and call!
* you can run `debug_match_dict = replacy.utils.attach_debug_hook(your_match_dict)` and then every match has the debug hook, so you can see why it matched and the match name
* new default hooks:

**Comment by sam-qordoba** [comment]
This should be a major version bump. 1.0.0 baby!

**Comment by sam-qordoba** [comment]
Also, you should add yourself to the README `citation` section 💪

**Comment by manhal-daaboul** [comment]
@sam-qordoba if you are ok with this PR, would you please approve it, so I can use a published version next week, easier than git dep

**Review by sam-qordoba — APPROVED** [review]
sorry for the slow approval, I was on PTO

**Pull request merged**
